### ISSUE TITLE
XML feed contains links to localhost

### ISSUE THREAD

**Issue by heitorPB** [satlive/website#58] opened 2019-11-12 02:16 UTC
The current deployed [feed.xml](http://www.satlive.org/feed.xml) contains several links to `localhost:4000`, but it should be `http://www.satlive.org/` instead.

How was the site built?

**Comment by satlive** [comment] 2019-11-12 06:29
As usual, using `jekyll serve`

I had to update to the latest version of jekyll two days ago. Maybe something changed in a recent release?

**Comment by satlive** [comment] 2019-11-12 06:34
I just used `jekyll build` instead.

I checked the feed.xml file. It no longer contains any reference to localhost.

**Comment by heitorPB** [comment] 2019-11-12 11:55
`jekyll build` is the way to go. Thank you for the quick response.

Have a nice day!

**Comment by satlive** [comment] 2019-11-12 12:10
Your are welcome.

I let you close the issue if the problem is solved.

**Closed** 2019-11-12 12:54 UTC
